<table>
<tbody>
   <tr id="row_vishal_whatsappchat_display_schedule">
      <td class="value">
         <div id="scheduleContainer">
            <div class="clean"></div>
         </div>
         <?php
          $storeId =  Mage::app()->getStore()->getStoreId();
          $schedule_time = Mage::getStoreConfig('vishal_whatsapp/display/schedule', $storeId);
          if(!$schedule_time)
          {
            $schedule_time = '[{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"},{"isActive":true,"timeFrom":"00:00","timeTill":"23:59"}]';
          }
         ?>
		<script>
		var businessHoursManager = jQuery("#scheduleContainer").businessHours({
    		operationTime:<?php echo $schedule_time;?>,
    		weekdays:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    		defaultOperationTimeFrom:"00:00",
    		defaultOperationTimeTill:"23:59",
    		postInit:function(){
	        	jQuery(".operationTimeFrom, .operationTimeTill").timepicker({
    	    		"timeFormat": "h:i a",
        			"step": 15
				});
    		},
    		dayTmpl:"<div class='dayContainer' style='width: 80px;'>" +
    		 "<div data-original-title='' class='colorBox'>" +
    		 	"<input type='checkbox' class='invisible operationState'>" +
    		 "</div>" +
    		 "<div class='weekday'></div>" +
    		 "<div class='operationDayTimeContainer'>" +
    		 	"<div class='operationTime input-group'>" +
    		 		"<span class='input-group-addon'>" +
    		 			"<i class='icon icon-sun'></i>" +
    		 		"</span>" +
    		 		"<input type='text' name='startTime' class='mini-time form-control operationTimeFrom' value=''>" +
    		 	"</div>" +
    		 	"<div class='operationTime input-group'>" +
    		 		"<span class='input-group-addon'><i class='icon icon-moon'></i></span>" +
    		 		"<input type='text' name='endTime' class='mini-time form-control operationTimeTill' value=''>" +
    		 	"</div>" +
    		 "</div></div>"});
		jQuery("document").ready(function() {
       jQuery("input#vishal_whatsappchat_display_schedule").val(JSON.stringify(businessHoursManager.serialize()));
		    jQuery("div#scheduleContainer").on("click", function() {
		        jQuery("input#vishal_whatsappchat_display_schedule").val("");
		        jQuery("input#vishal_whatsappchat_display_schedule").val(JSON.stringify(businessHoursManager.serialize()));
		    });
		    jQuery("input.mini-time").each(function() {
				jQuery(this).change(function() {
		        jQuery("input#vishal_whatsappchat_display_schedule").val("");
		        jQuery("input#vishal_whatsappchat_display_schedule").val(JSON.stringify(businessHoursManager.serialize()));
				});
		    });
		});
		</script>
  <input id="vishal_whatsappchat_display_schedule" name="groups[display][fields][schedule][value]" value="" type="hidden">
</td>
<td class=""></td>
</tr>
</tbody>
</table>