<?php
/**
 * Vishal_Whatsapp extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Vishal
 * @package        Vishal_Whatsapp
 * @copyright      Copyright (c) 2018
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Whatsapp link widget template
 *
 * @category    Vishal
 * @package     Vishal_Whatsapp
 * @author      Ultimate Module Creator
 */
?>
<?php $_whatsapp = $this->getCurrentWhatsapp();?>
<?php if ($_whatsapp) :?>
    <div class="whatsapp-widget-link">
        <a href="<?php echo $_whatsapp->getWhatsappUrl()?>"><?php echo $_whatsapp->getMobilePhone()?></a>
    </div>
<?php endif;?>
